# Generated by Django 2.0.3 on 2018-03-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_roles',
            field=models.ManyToManyField(related_name='allowed_users', to='auth.Group'),
        ),
    ]
