# Generated by Django 2.0.3 on 2018-03-25 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180325_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lane',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lanes', to='projects.Project'),
        ),
    ]
