# Generated by Django 2.0.3 on 2018-04-17 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20180417_1136'),
        ('projects', '0008_auto_20180417_2003'),
    ]

    operations = [
    ]
