# Generated by Django 2.0.3 on 2018-04-17 21:01

from django.db import migrations


def create_column(apps, schema_editor):
    Column = apps.get_model('projects', 'Column')
    Card = apps.get_model('projects', 'Card')
    column = Column.objects.create(name='placeholder', card_limit=15)
    for card in Card.objects.all():
        if card.column is None:
            card.column = column
            card.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20180417_2259'),
    ]

    operations = [
        migrations.RunPython(create_column)
    ]
