# Generated by Django 2.0.3 on 2018-04-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20180417_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dev_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dev_groups.DevGroup'),
        ),
    ]
