# Generated by Django 2.0.3 on 2018-04-19 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20180418_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.Card'),
        ),
    ]
