# Generated by Django 2.0.3 on 2018-04-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20180420_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lane',
            name='board',
        ),
        migrations.RemoveField(
            model_name='lane',
            name='columns',
        ),
        migrations.AddField(
            model_name='column',
            name='lane',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='projects.Lane'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.Board'),
        ),
    ]
