# Generated by Django 2.0.3 on 2018-04-20 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20180420_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='lane',
        ),
        migrations.AlterField(
            model_name='card',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='projects.Column'),
        ),
    ]
