# Generated by Django 2.0.3 on 2018-04-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20180420_1810'),
        ('projects', '0017_project_codename'),
    ]

    operations = [
    ]
