# Generated by Django 2.0.3 on 2018-04-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20180420_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='codename',
            field=models.CharField(default='asjkdfhasjd', max_length=512),
            preserve_default=False,
        ),
    ]
