# Generated by Django 2.0.3 on 2018-04-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_card_codename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='codename',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
