# Generated by Django 2.0.3 on 2018-04-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20180421_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='lane',
        ),
        migrations.AddField(
            model_name='card',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='column',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='projects.Board'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lane',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lane', to='projects.Project'),
        ),
    ]
