# Generated by Django 2.0.3 on 2018-04-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20180421_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lane',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lane',
            name='order',
        ),
    ]
