# Generated by Django 2.0.3 on 2018-04-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20180421_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='column_type',
            field=models.PositiveIntegerField(choices=[(1, 'Requested'), (2, 'In progress'), (3, 'Done')], default=1),
            preserve_default=False,
        ),
    ]
