# Generated by Django 2.0.3 on 2018-04-22 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0030_column_column_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WIPViolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='card',
            name='development_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wipviolation',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wip_violations', to='projects.Card'),
        ),
        migrations.AddField(
            model_name='wipviolation',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wip_violations', to='projects.Column'),
        ),
        migrations.AddField(
            model_name='wipviolation',
            name='violation_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wip_violations', to=settings.AUTH_USER_MODEL),
        ),
    ]
