# Generated by Django 2.0.3 on 2018-05-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20180422_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
