# Generated by Django 2.0.3 on 2018-05-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20180422_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='dAttr',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
