# Generated by Django 2.0.3 on 2018-05-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20180504_0955'),
        ('projects', '0033_board_dattr'),
    ]

    operations = [
    ]
