# Generated by Django 2.0.3 on 2018-05-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_auto_20180523_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='column_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Requested'), (2, 'In progress'), (3, 'Done')], null=True),
        ),
    ]
