sudo: required

language: generic

services:
  - docker

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USER --password-stdin
  - docker build -t ak2748/smrpo-django:latest .
  - docker push ak2748/smrpo-django:latest