# Generated by Django 2.0.3 on 2018-04-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_groups', '0002_auto_20180322_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='date_removed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
