# Generated by Django 2.0.3 on 2018-04-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_groups', '0003_membership_date_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateTimeField(),
        ),
    ]
