# Generated by Django 2.0.3 on 2018-04-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_groups', '0004_auto_20180420_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
